import TrainingLayout from "../components/layout/TrainingLayout/TrainingLayout";

function Training() {
    return (
        <TrainingLayout header="Designing The Ultimate Calculator" loomEmedLink="https://www.loom.com/embed/eb6436dfadb24ad8a6955f02f6e747c3">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fringilla quis etiam vitae hendrerit pharetra sit sapien justo, molestie. Ut libero mi faucibus vitae vestibulum amet, erat. Non auctor in arcu nunc lectus lacus mauris lacus. Commodo non molestie vitae quis neque. Diam quis nibh risus, ac aliquet sed bibendum. Lacus in et arcu quam non habitant. Proin velit adipiscing quis nibh pellentesque aenean lacinia. Ultrices dignissim non, sodales ultrices pellentesque cursus faucibus cras mattis. Eu amet eu, enim egestas amet. Commodo, nec, risus, ipsum sapien. Elit condimentum augue commodo rhoncus metus. Purus viverra pretium mauris, ac. Id nisl a varius condimentum purus elit, quam. Tempor nibh amet, nec adipiscing donec.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fringilla quis etiam vitae hendrerit pharetra sit sapien justo, molestie. Ut libero mi faucibus vitae vestibulum amet, erat. Non auctor in arcu nunc lectus lacus mauris lacus. Commodo non molestie vitae quis neque. Diam quis nibh risus, ac aliquet sed bibendum. Lacus in et arcu quam non habitant. Proin velit adipiscing quis nibh pellentesque aenean lacinia. Ultrices dignissim non, sodales ultrices pellentesque cursus faucibus cras mattis. Eu amet eu, enim egestas amet. Commodo, nec, risus, ipsum sapien. Elit condimentum augue commodo rhoncus metus. Purus viverra pretium mauris, ac. Id nisl a varius condimentum purus elit, quam. Tempor nibh amet, nec adipiscing donec.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fringilla quis etiam vitae hendrerit pharetra sit sapien justo, molestie. Ut libero mi faucibus vitae vestibulum amet, erat. Non auctor in arcu nunc lectus lacus mauris lacus. Commodo non molestie vitae quis neque. Diam quis nibh risus, ac aliquet sed bibendum. Lacus in et arcu quam non habitant. Proin velit adipiscing quis nibh pellentesque aenean lacinia. Ultrices dignissim non, sodales ultrices pellentesque cursus faucibus cras mattis. Eu amet eu, enim egestas amet. Commodo, nec, risus, ipsum sapien. Elit condimentum augue commodo rhoncus metus. Purus viverra pretium mauris, ac. Id nisl a varius condimentum purus elit, quam. Tempor nibh amet, nec adipiscing donec.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fringilla quis etiam vitae hendrerit pharetra sit sapien justo, molestie. Ut libero mi faucibus vitae vestibulum amet, erat. Non auctor in arcu nunc lectus lacus mauris lacus. Commodo non molestie vitae quis neque. Diam quis nibh risus, ac aliquet sed bibendum. Lacus in et arcu quam non habitant. Proin velit adipiscing quis nibh pellentesque aenean lacinia. Ultrices dignissim non, sodales ultrices pellentesque cursus faucibus cras mattis. Eu amet eu, enim egestas amet. Commodo, nec, risus, ipsum sapien. Elit condimentum augue commodo rhoncus metus. Purus viverra pretium mauris, ac. Id nisl a varius condimentum purus elit, quam. Tempor nibh amet, nec adipiscing donec.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fringilla quis etiam vitae hendrerit pharetra sit sapien justo, molestie. Ut libero mi faucibus vitae vestibulum amet, erat. Non auctor in arcu nunc lectus lacus mauris lacus. Commodo non molestie vitae quis neque. Diam quis nibh risus, ac aliquet sed bibendum. Lacus in et arcu quam non habitant. Proin velit adipiscing quis nibh pellentesque aenean lacinia. Ultrices dignissim non, sodales ultrices pellentesque cursus faucibus cras mattis. Eu amet eu, enim egestas amet. Commodo, nec, risus, ipsum sapien. Elit condimentum augue commodo rhoncus metus. Purus viverra pretium mauris, ac. Id nisl a varius condimentum purus elit, quam. Tempor nibh amet, nec adipiscing donec.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fringilla quis etiam vitae hendrerit pharetra sit sapien justo, molestie. Ut libero mi faucibus vitae vestibulum amet, erat. Non auctor in arcu nunc lectus lacus mauris lacus. Commodo non molestie vitae quis neque. Diam quis nibh risus, ac aliquet sed bibendum. Lacus in et arcu quam non habitant. Proin velit adipiscing quis nibh pellentesque aenean lacinia. Ultrices dignissim non, sodales ultrices pellentesque cursus faucibus cras mattis. Eu amet eu, enim egestas amet. Commodo, nec, risus, ipsum sapien. Elit condimentum augue commodo rhoncus metus. Purus viverra pretium mauris, ac. Id nisl a varius condimentum purus elit, quam. Tempor nibh amet, nec adipiscing donec.</p>
        </TrainingLayout>
    )
}

export default Training;